### ISSUE TITLE
Why do I need to configure each install id in keysfile with secret?

### ISSUE THREAD

**Issue by discordianfish** [QubitProducts/kube-ci#1]
The keysfile contains the install IDs and the application secret. That confuses me. The private key is per application, why do I need to configure it 'per install' in the config? Isn't this always the same?

**Comment by tcolgate** [comment]
This came from a misunderstanding of how I stall IDs could work for multi org deploys. Happy to take alternate suggestions.

**Comment by tcolgate** [comment]
This is fixed in master.
