### ISSUE TITLE
Allow non-DNS compatible branch names

### ISSUE THREAD

**Issue by tcolgate** [QubitProducts/kube-ci#3]
Because we put the branch name in a label, and labels must be DNS name compatible, we can't support branches with /, or other non-DNS suitable chars.

DNS names are too restricted to permit escaping, so either we probably need to move the branch name to an annotation, or similar,  assuming we don't use branch name for label matching (which I think maybe we do).

**Comment by zoltanarvai** [comment]
@tcolgate Additionally I discovered yesterday that slashes in branch names also cause issues for switching to remote branches in Shelly. It is unrelated but it seams using them is just not supported at all. Worth considering if the change is required at all.
